server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql